#!/bin/bash

conf_file=/etc/salarm/global.conf

if [[ -e $conf_file ]];then
  source $conf_file
fi

ADB_SHELL_SU=${ADB_SHELL_SU:-1}

if [[ $ADB_SHELL_SU == 1 ]] ; then
  if [[ $ADB_SHELL_USE_PIPE ]] ;  then
      # if we need to type a command with a pipe inbetween
      echo "$@ ; exit" | adb shell su root sh
  else
      adb shell su root "$@"
  fi
else
  if [[ $ADB_SHELL_USE_PIPE ]] ;  then
      # if we need to type a command with a pipe inbetween
      echo "$@ ; exit" | adb shell sh
  else
      adb shell "$@"
  fi
fi
